# Generated by Django 5.2.7 on 2025-11-11 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comptetiktok',
            unique_together={('user', 'username')},
        ),
    ]
