# Generated by Django 5.2.7 on 2025-12-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_comptetiktok_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseDiscours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('neutre', 'Neutre'), ('polemique', 'Polémique'), ('viral', 'Potentiellement viral'), ('haineux', 'Discours haineux')], max_length=20)),
                ('viralite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('forte', 'Forte')], max_length=10)),
                ('discours_haineux', models.BooleanField(default=False, help_text='Indique si un discours haineux a été détecté')),
                ('cible', models.CharField(blank=True, help_text='Cible du discours haineux (si détecté)', max_length=100)),
                ('justification', models.TextField(help_text="Explication de l'analyse")),
                ('risque_score', models.FloatField(help_text='Score de risque (0.0 à 1.0)')),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analyse de discours',
                'verbose_name_plural': 'Analyses de discours',
                'ordering': ['-risque_score', '-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='AlerteModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examinée'), ('action_taken', 'Action effectuée'), ('dismissed', 'Ignorée')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('action_effectuee', models.TextField(blank=True, help_text="Description de l'action prise")),
                ('admin_notifie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_recues', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='tracking.analysediscours')),
            ],
            options={
                'verbose_name': 'Alerte de modération',
                'verbose_name_plural': 'Alertes de modération',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.PositiveIntegerField(help_text='Numéro du segment (ordre chronologique)')),
                ('text', models.TextField(help_text='Texte transcrit du segment audio')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Horodatage de la transcription')),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='tracking.live')),
            ],
            options={
                'ordering': ['segment_number'],
                'unique_together': {('live', 'segment_number')},
            },
        ),
        migrations.AddField(
            model_name='analysediscours',
            name='transcription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='tracking.transcription'),
        ),
    ]
