# Generated by Django 5.2.7 on 2025-12-28 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_analysediscours_alertemoderation_transcription_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcription',
            unique_together={('live', 'segment_number', 'timestamp')},
        ),
    ]
